spring.application.name=notification-service
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.auto-create=true

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer
spring.kafka.consumer.group-id=notification-service
spring.kafka.listener.concurrency=3

# Topics
app.kafka.topic.notifications=notification.events
app.kafka.topic.notifications-dlt=notification.events-dlt

# Logging
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
